name: StormEvents
version: '${project.version}'
main: me.fbiflow.stormevents.Plugin
depend:
  - WorldEdit
api-version: '1.16'
commands:
  reload-plugin:
    usage: "reload"
    permission: "stormevents.reload"
    aliases:
      - reloadconfig
    description: "reload config"
    permission-message: "you dont have permission to reload config"